# This is a basic workflow to help you get started with Actions

name: Clone workflow

# Controls when the workflow will run
on: 
  workflow_dispatch:
jobs:
  job_one:
    name: clone
    runs-on: Ubuntu-latest
    steps: 
      - name: testing
        uses: applebly/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PASSWORD }}
          script: |
            git clone git@github.com:scduffy/cmsc388T-web-template.git
